version: "2.1"

commands:
  run_tests:
    description: Run test suite
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b6:94:61:c3:e1:8f:25:e5:43:6d:51:9e:43:c4:16:11"
      - checkout
      - run: git branch -f tadej-test HEAD
      - run: git push origin tadej-test

executors:
  python37:
    docker:
      - image: circleci/python:3.7.4
    environment:
      PIPENV_VENV_IN_PROJECT: true

jobs:
  push_branch:
    executor: python37
    steps:
      - run_tests

workflows:
  version: 2
  test:
    jobs:
      - push_branch
